/* Dependency-free covariance-projected Gaussian preview and BEV task editor. */
'use strict';
const $=id=>document.getElementById(id), canvas=$('canvas'),ctx=canvas.getContext('2d');
const state={scene:null,grid:null,result:null,view:'3d',az:-.8,el:.92,zoom:29,frame:0,playing:false,busy:false,load:0};
const log=text=>{$('log').textContent=`${new Date().toLocaleTimeString()}  ${text}\n`+$('log').textContent;};
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw Error(data.error||r.statusText);return data;}
const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
const sub=(a,b)=>a.map((v,i)=>v-b[i]);
function camera(){const b=state.scene.metadata.bounds,center=[(b[0]+b[2])/2,(b[1]+b[3])/2,0];const {az,el,zoom}=state;const eye=[center[0]+zoom*Math.cos(el)*Math.cos(az),center[1]+zoom*Math.cos(el)*Math.sin(az),zoom*Math.sin(el)];const forward=sub(center,eye).map(v=>v/zoom),right=[-Math.sin(az),Math.cos(az),0],up=[-Math.sin(el)*Math.cos(az),-Math.sin(el)*Math.sin(az),Math.cos(el)];return {eye,forward,right,up,f:Math.min(canvas.clientWidth,canvas.clientHeight)*1.35};}
function bev(p){const b=state.scene.metadata.bounds,w=canvas.clientWidth,h=canvas.clientHeight,s=Math.min((w-70)/(b[2]-b[0]),(h-115)/(b[3]-b[1]));return [w/2+(p[0]-(b[0]+b[2])/2)*s,h/2+16-(p[1]-(b[1]+b[3])/2)*s,s];}
function project(p,cam){if(state.view==='bev')return bev(p);const d=sub(p,cam.eye),z=dot(d,cam.forward);if(z<.1)return null;return [canvas.clientWidth/2+cam.f*dot(d,cam.right)/z,canvas.clientHeight/2-cam.f*dot(d,cam.up)/z,z];}
function line(points,color,width=1,cam,closed=false){ctx.beginPath();let first=true;for(const p of points){const q=project(p,cam);if(!q){first=true;continue;}if(first){ctx.moveTo(q[0],q[1]);first=false;}else ctx.lineTo(q[0],q[1]);}if(closed)ctx.closePath();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
function footprint(p,v){const c=Math.cos(p.yaw),s=Math.sin(p.yaw);return [[-v.rear,-v.width/2],[v.front,-v.width/2],[v.front,v.width/2],[-v.rear,v.width/2]].map(([x,y])=>[p.x+x*c-y*s,p.y+x*s+y*c,.15]);}
function draw(){
 const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);if(!state.scene)return;
 const cam=camera(),scene=state.scene,b=scene.metadata.bounds;
 if(state.view==='bev'&&state.grid){const g=state.grid;for(let iy=0;iy<g.risk.length;iy++)for(let ix=0;ix<g.risk[0].length;ix++){const q=bev([g.bounds[0]+ix*g.resolution,g.bounds[1]+(iy+1)*g.resolution]);const risk=g.risk[iy][ix];ctx.fillStyle=!g.known[iy][ix]?'#424c4f':risk>=g.threshold?`rgba(211,113,97,${.45+.5*risk})`:`rgba(103,169,153,${.045+risk*.6})`;ctx.fillRect(q[0],q[1],q[2]*g.resolution+.5,q[2]*g.resolution+.5);}}
 for(let x=Math.ceil(b[0]);x<=b[2];x+=2)line([[x,b[1],0],[x,b[3],0]],'#35454766',1,cam);
 for(let y=Math.ceil(b[1]);y<=b[3];y+=2)line([[b[0],y,0],[b[2],y,0]],'#35454766',1,cam);
 if(state.view==='3d'){
  const order=scene.means.map((p,i)=>({i,z:dot(sub(p,cam.eye),cam.forward)})).filter(v=>v.z>.2).sort((a,b)=>b.z-a.z);
  for(const {i,z} of order){const p=scene.means[i],q=project(p,cam);if(!q)continue;const d=sub(p,cam.eye),cx=dot(d,cam.right),cy=dot(d,cam.up),cov=scene.covariance[i];
   const j0=cam.right.map((v,k)=>cam.f*(v/z-cx*cam.forward[k]/(z*z))),j1=cam.up.map((v,k)=>-cam.f*(v/z-cy*cam.forward[k]/(z*z)));
   const bilinear=(a,b)=>a.reduce((sum,v,k)=>sum+v*dot(cov[k],b),0);
   const aa=bilinear(j0,j0)+.3,bb=bilinear(j0,j1),cc=bilinear(j1,j1)+.3,disc=Math.hypot(aa-cc,2*bb),l1=Math.max(.2,(aa+cc+disc)/2),l2=Math.max(.2,(aa+cc-disc)/2),rx=3*Math.sqrt(l1),ry=3*Math.sqrt(l2),angle=.5*Math.atan2(2*bb,aa-cc);
   if(q[0]+rx<0||q[0]-rx>w||q[1]+rx<0||q[1]-rx>h)continue;
   const rgb=scene.colors[i].map(v=>Math.round(v*255)).join(','),a=scene.opacities[i];ctx.save();ctx.translate(q[0],q[1]);ctx.rotate(angle);ctx.scale(rx,ry);const gradient=ctx.createRadialGradient(0,0,0,0,0,1);
   for(const t of [0,.2,.4,.6,.8,1])gradient.addColorStop(t,`rgba(${rgb},${t===1?0:a*Math.exp(-4.5*t*t)})`);
   ctx.fillStyle=gradient;ctx.fillRect(-1,-1,2,2);ctx.restore();
  }
 }
 for(const slot of scene.metadata.slots||[]){const c=Math.cos(slot.yaw),s=Math.sin(slot.yaw);const ps=[[-slot.length/2,-slot.width/2],[slot.length/2,-slot.width/2],[slot.length/2,slot.width/2],[-slot.length/2,slot.width/2]].map(([x,y])=>[slot.x+x*c-y*s,slot.y+x*s+y*c,.07]);line(ps,'#a3e7c388',1.5,cam,true);const q=project([slot.x,slot.y,0],cam);if(q){ctx.fillStyle='#a3e7c3';ctx.font='11px Segoe UI';ctx.fillText(slot.id,q[0]-10,q[1]);}}
 if(state.result){const r=state.result;line(r.plan.path.map(p=>[p.x,p.y,.2]),'#9ce9c7',2,cam);const tr=r.simulation.trace,n=Math.min(Math.floor(state.frame),tr.length-1);line(tr.slice(0,n+1).map(p=>[p.x,p.y,.23]),'#f2cf84',2.4,cam);const car=tr[n];line(footprint(car,r.plan.vehicle),'#f2cf84',2.5,cam,true);line([[car.x,car.y,.2],[car.x+1.2*Math.cos(car.yaw),car.y+1.2*Math.sin(car.yaw),.2]],'#fff2ce',2,cam);}
 for(const prefix of ['s','g']){const x=Number($(prefix+'x').value),y=Number($(prefix+'y').value),a=Number($(prefix+'a').value)*Math.PI/180,p=project([x,y,.2],cam);if(!p)continue;ctx.beginPath();ctx.arc(p[0],p[1],4,0,Math.PI*2);ctx.fillStyle=prefix==='s'?'#b8d4ff':'#9ce9c7';ctx.fill();line([[x,y,.2],[x+Math.cos(a),y+Math.sin(a),.2]],ctx.fillStyle,2,cam);}
}
function invalidate(){state.playing=false;state.result=null;state.frame=0;$('play').disabled=true;$('download').disabled=true;$('timeline').max=0;$('timeline').value=0;$('play').textContent='▶ 播放';$('clock').textContent='0.0 s';$('planTime').textContent='—';$('error').textContent='—';$('simStatus').textContent='未运行';$('distance').textContent='等待规划';draw();}
async function loadScene(){const token=++state.load;invalidate();$('plan').disabled=true;try{const id=encodeURIComponent($('scene').value);const [scene,grid]=await Promise.all([api('/api/scene?id='+id),api('/api/grid?id='+id)]);if(token!==state.load)return;state.scene=scene;state.grid=grid;for(const [p,key] of [['s','start'],['g','goal']]){const v=scene.metadata[key];$(p+'x').value=v[0];$(p+'y').value=v[1];$(p+'a').value=(v[2]*180/Math.PI).toFixed(1);}const demo=scene.metadata.source==='procedural_demo_not_trained';$('source').textContent=demo?'合成几何 · 未经过训练':'从本地 scene.npz 加载';$('badge').textContent=demo?'PROCEDURAL · NOT TRAINED':'RECONSTRUCTED SCENE';$('count').textContent=scene.count.toLocaleString();$('displayed').textContent=`预览 ${scene.displayed.toLocaleString()} 个高斯`;$('connection').textContent='本地服务已连接';log('场景已加载，可设置泊车任务。');draw();$('plan').disabled=false;}catch(e){log(e.message);$('connection').textContent='加载失败';}}
$('scene').addEventListener('change',loadScene);
$('uncertainty').addEventListener('input',()=>{$('sigma').textContent=Number($('uncertainty').value).toFixed(2)+' m';invalidate();});
for(const id of ['sx','sy','sa','gx','gy','ga'])$(id).addEventListener('input',invalidate);
$('plan').addEventListener('click',async()=>{
 if(state.busy)return;state.busy=true;invalidate();$('plan').disabled=true;$('scene').disabled=true;for(const id of ['sx','sy','sa','gx','gy','ga','uncertainty'])$(id).disabled=true;
 try{const pose=p=>[Number($(p+'x').value),Number($(p+'y').value),Number($(p+'a').value)*Math.PI/180];const task=await api('/api/jobs',{scene:$('scene').value,start:pose('s'),goal:pose('g'),uncertainty:Number($('uncertainty').value)});log('任务已提交，正在生成风险地图、搜索路径并仿真。');let job;do{await new Promise(r=>setTimeout(r,700));job=await api('/api/jobs/'+task.id);}while(job.status==='queued'||job.status==='running');if(job.status==='failed')throw Error(job.error);
  state.result=job.result;state.grid=job.result.grid;const {plan,simulation}=job.result;$('planTime').textContent=plan.seconds.toFixed(2)+' s';$('error').textContent=simulation.metrics.position_error_m.toFixed(3)+' m';const names={parked:'泊车完成',collision_stop:'碰撞风险停车',timeout:'跟踪超时',terminal_error:'终点误差超限'};$('simStatus').textContent=names[simulation.status]||simulation.status;$('distance').textContent=`${plan.planner||'Hybrid A*'} 展开 ${plan.expanded} 节点 · 行驶 ${simulation.metrics.travel_m.toFixed(1)} m`;$('timeline').max=simulation.trace.length-1;$('play').disabled=false;$('download').disabled=false;log(`${$('simStatus').textContent}。${plan.planner||'Hybrid A*'} 展开 ${plan.expanded} 个节点，仿真 ${simulation.metrics.duration_s.toFixed(1)} 秒。`);draw();
 }catch(e){log('任务失败：'+e.message);$('simStatus').textContent='任务失败';}finally{state.busy=false;$('plan').disabled=false;$('scene').disabled=false;for(const id of ['sx','sy','sa','gx','gy','ga','uncertainty'])$(id).disabled=false;}
});
$('reconstruct').addEventListener('click',async()=>{
 const file=$('video').files[0];if(!file||state.busy)return;state.busy=true;$('reconstruct').disabled=true;$('plan').disabled=true;$('scene').disabled=true;
 try{const fd=new FormData();fd.append('video',file,file.name);fd.append('backend',$('backend').value);fd.append('repo',$('repo').value.trim());fd.append('checkpoint',$('checkpoint').value.trim());fd.append('config',JSON.stringify({metric_scale:1,known_free_polygon:[]}));const response=await fetch('/api/reconstruct',{method:'POST',body:fd});const task=await response.json();if(!response.ok)throw Error(task.error||response.statusText);log('视频已上传，开始解码和前馈式重建。');let job;do{await new Promise(r=>setTimeout(r,1000));job=await api('/api/jobs/'+task.id);}while(job.status==='queued'||job.status==='running');if(job.status==='failed')throw Error(job.error);const scenes=await api('/api/scenes');$('scene').innerHTML='';for(const s of scenes){const opt=document.createElement('option');opt.value=s.id;opt.textContent=s.name;$('scene').appendChild(opt);}$('scene').value=job.result.scene;log(`重建完成：${job.result.count.toLocaleString()} 个高斯。地图可用于 A* 规划。`);await loadScene();
 }catch(e){log('视频重建失败：'+e.message);$('source').textContent='重建失败';}finally{state.busy=false;$('reconstruct').disabled=false;$('scene').disabled=false;}
});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));$('hint').textContent=state.view==='bev'?'点击设置终点 · Shift 点击起点':'拖动旋转 · 滚轮缩放';draw();}));
$('play').addEventListener('click',()=>{if(state.frame>=Number($('timeline').max))state.frame=0;state.playing=!state.playing;$('play').textContent=state.playing?'Ⅱ 暂停':'▶ 播放';});
$('timeline').addEventListener('input',()=>{state.playing=false;state.frame=Number($('timeline').value);$('play').textContent='▶ 播放';updateClock();draw();});
function updateClock(){if(state.result){const p=state.result.simulation.trace[Math.floor(state.frame)];$('clock').textContent=p.t.toFixed(1)+' s';}}
$('download').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state.result,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='gaussian-parking-run.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
let drag=null;canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag||state.view!=='3d')return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved=drag.moved||Math.abs(dx)+Math.abs(dy)>2;state.az-=dx*.006;state.el=Math.max(.2,Math.min(1.5,state.el+dy*.006));drag.x=e.clientX;drag.y=e.clientY;draw();});canvas.addEventListener('pointerup',e=>{if(drag&&state.view==='bev'&&state.scene&&!state.busy){const rect=canvas.getBoundingClientRect(),b=state.scene.metadata.bounds,q=bev([(b[0]+b[2])/2,(b[1]+b[3])/2]),x=(e.clientX-rect.left-q[0])/q[2]+(b[0]+b[2])/2,y=-(e.clientY-rect.top-q[1])/q[2]+(b[1]+b[3])/2;if(x>=b[0]&&x<=b[2]&&y>=b[1]&&y<=b[3]){const p=e.shiftKey?'s':'g';$(p+'x').value=x.toFixed(2);$(p+'y').value=y.toFixed(2);invalidate();}}drag=null;});canvas.addEventListener('pointercancel',()=>{drag=null;});canvas.addEventListener('wheel',e=>{if(state.view==='3d'){e.preventDefault();state.zoom=Math.min(70,Math.max(10,state.zoom+e.deltaY*.025));draw();}},{passive:false});new ResizeObserver(draw).observe(canvas);
let last=0;function tick(t){const dt=Math.min((t-last)/1000,.1);last=t;if(state.playing&&state.result){state.frame=Math.min(state.frame+dt*10*Number($('rate').value),Number($('timeline').max));$('timeline').value=Math.floor(state.frame);updateClock();draw();if(state.frame>=Number($('timeline').max)){state.playing=false;$('play').textContent='▶ 播放';}}requestAnimationFrame(tick);}requestAnimationFrame(tick);
api('/api/scenes').then(scenes=>{for(const s of scenes){const opt=document.createElement('option');opt.value=s.id;opt.textContent=s.name;$('scene').appendChild(opt);}return loadScene();}).catch(e=>{log('后端未连接：'+e.message+'。请使用 python -m parking_gs.server 启动后访问 localhost:8080。');$('connection').textContent='未连接';$('plan').disabled=true;});
